### ISSUE TITLE
Checkpoint file

### ISSUE THREAD

**Issue by chenzb0712** [ssuralcmu/ContextualFusion#1]
Hello! I want to run your model.  Can you provide the checkpoint file?

**Comment by ssuralcmu** [comment]
Apologies for the late response. The checkpoints are available at- https://cmu.box.com/s/au4v02xcy1iwjv9hsrn70ej6ddkh40w1

**Comment by jorgemn9** [comment]
Hi @ssuralcmu! Would you be so kind to also upload the "configs.yaml" file of the training please? Thanks in advance
